### ISSUE TITLE
Fix typo in Navbar

### ISSUE THREAD

**Issue by JP-Go** [ailsonazevedo/pokedex-next#2]
### O problema:

Na barra de navegação, no estado atual do branch `main`, há um erro de ortografia. A palavra 'Contact' está escrita como 'Contatc'

### Provável solução:

A maneira mais fácil de corrigir o problema é, no componente `Navbar`, trocar a palavra 'Contatc' para 'Contact'

**Comment by ailsonazevedo** [comment]
valeu :)
